# fly.toml app configuration file generated for coding-school-list on 2023-05-29T21:25:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coding-school-list"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
